/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.ids.dharma.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
